export const playerConstants = {
    
    LOGIN_REQUEST: '@@PLAYERS/USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: '@@PLAYERS/USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: '@@PLAYERS/USERS_LOGIN_FAILURE',
    
    LOGOUT: '@@PLAYERS/USERS_LOGOUT',

    REGISTER_REQUEST: '@@PLAYERS/REGISTER_REQUEST',
    REGISTER_SUCCESS: '@@PLAYERS/REGISTER_SUCCESS',
    REGISTER_FAILURE: '@@PLAYERS/REGISTER_FAILURE',

    UPDATE_REQUEST: '@@PLAYERS/UPDATE_REQUEST',
    UPDATE_SUCCESS: '@@PLAYERS/UPDATE_SUCCESS',
    UPDATE_FAILURE: '@@PLAYERS/UPDATE_FAILURE',
    
    GETALL_REQUEST: '@@PLAYERS/GETALL_REQUEST',
    GETALL_SUCCESS: '@@PLAYERS/GETALL_SUCCESS',
    GETALL_FAILURE: '@@PLAYERS/GETALL_FAILURE',

    GETWINNERS_REQUEST: '@@PLAYERS/WINNERS_REQUEST',
    GETWINNERS_SUCCESS: '@@PLAYERS/WINNERS_SUCCESS',
    GETWINNERS_FAILURE: '@@PLAYERS/WINNERS_FAILURE',
    SET_CURRENT_PLAYER: '@@PLAYERS/SET_CURRENT_PLAYER'
};
